title: "Raeuf Roushangar"
email: "rroushangar19@gmail.com"
description: "Interdisciplinary Computational Scientist"
baseurl: "https://raeufroushangar.github.io/my-site"  # Adjust with your specific URL
# url: "https://raeufroushangar.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Social
linkedin_username: raeufroushangar
github_username: raeufroushangar

sass:
  style: compressed

markdown: kramdown

theme: minima

plugins:
  - jekyll-feed

include:
  - assets/css/style.css

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
